Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,6 +1,6 @@
-# This is a basic workflow that is manually triggered
+# Checks a branch upon pull request, and checks the master build when there are new commits
 
-name: Manual workflow
+name: Check Commits
 
 # Controls when the action will run. Workflow runs when manually triggered using the UI
 # or API.
@@ -9,40 +9,96 @@ on: [push, pull_request]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # Our first job, Checkstyle (using clang-tidy)
-  Checkstyle:
-    # The type of runner that the job will run on, windows in our case.
+  # Run clang-format and clang-tidy
+  clang-checks:
+    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      - name: Checkout code from Github
+      - name: Checkout code from GitHub
         uses: actions/checkout@v2
-      - name: Clang tidy
+        
+      - name: Cache dependencies
+        id: cache-deps
+        uses: actions/cache@v2
+        with:
+          path: ~/cache
+          key: ${{ runner.os }}-spa-clang-checks-deps
+
+      - name: Generate dependencies
+        env:
+          CACHE_HIT: ${{ steps.cache-deps.outputs.cache-hit }}
         run: |
-          sudo apt-get install clang-tidy
+            if [[ "$CACHE_HIT" == 'true' ]]; then
+              sudo cp --verbose --force --recursive ~/cache/* /
+            else
+              sudo apt-get install clang-format-10
+              sudo apt-get install clang-tidy
+              mkdir -p ~/cache
+              sudo dpkg -L clang-format-10 \
+                | while IFS= read -r f; do if test -f $f; then echo $f; fi; done \
+                | xargs cp --parents --target-directory ~/cache/
+              sudo dpkg -L clang-tidy \
+                | while IFS= read -r f; do if test -f $f; then echo $f; fi; done \
+                | xargs cp --parents --target-directory ~/cache/
+            fi
+            
+      - name: Build SPA
+        run: |
           cd Team12/Code12/
           rm -f -r build
           mkdir build
           cd build
           cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
           make
-          curl https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py -o run-clang-tidy.py
-          python run-clang-tidy.py -header-filter='.*' -checks='-*,cppcoreguidelines-*,-cppcoreguidelines-owning-memory' files src/spa | tee result.txt
+          
+      - name: clang-format
+        run: |
+          projectfiles=$(find ./Team12/Code12/src/spa/src -iname "*.h" -o -iname "*.cpp")
+          exitcode=0
+          for f in $projectfiles;
+          do
+              outputname=$(echo "$f" | rev | cut -f 2 -d '.' | cut -f 1 -d '/' | rev)
+              rm -f $outputname.out.temp
+              clang-format-10 $f >> $outputname.out.temp
+              result=$(diff $f $outputname.out.temp)
+              if [ -z "$result" ];
+              then
+                  echo "$f formatted correctly!"
+                  echo ""
+              else
+                  echo "clang-format errors in $f"
+                  echo "$result"
+                  echo ""
+                  exitcode=1
+              fi
+          done
+          exit "$exitcode"
+            
+      - name: clang-tidy
+        run: |
+          cd Team12/Code12/build
+          curl https://raw.githubusercontent.com/llvm/llvm-project/master/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py -o run-clang-tidy.py
+          python run-clang-tidy.py -header-filter='.*' \
+            -checks='-*,cppcoreguidelines-*,-cppcoreguidelines-owning-memory' \
+            files src/spa | tee result.txt
           if grep -w "error:\|warning:\|Error while processing" result.txt; then
-          exit 1
+            exit 1
           else
-          exit 0
+            exit 0
           fi
-      - name: Autotester
+      
+      - name: Run SPA autotester
         run: |
           cd Team12/Code12/build/src/autotester/
           cp ../../../../Tests12/Sample_source.txt .
           cp ../../../../Tests12/Sample_queries.txt .
           ./autotester Sample_source.txt Sample_queries.txt out.xml
           if grep -w "failed" out.xml; then
-          exit 0
+            echo "Autotester failed"
+            exit 0
           else
-          exit 0
+            exit 0
           fi
 
